Repository PI2-viticultura/SmartVit-Administrator-API, pull requests merged in 2020-10, with the labels that each got.

#3 Cadastrar Contrato
  app/app.py
  app/controllers/contract.py
  app/extensions.py
  app/models/contract.py
  app/settings.py
  app/utils/constants.py
  app/views/contract.py
  docker-compose.yml
Labels: enhancement

#4 Feature/16 us32 cadastrar solicitacao
  app/app.py
  app/controllers/contract.py
  app/controllers/order.py
  app/models/db.py
  app/views/order.py
Labels: hacktoberfest-accepted

#5 Feature/19 us26 visualizar solicitações
  app/controllers/order.py
  app/models/db.py
  app/views/order.py
  requirements.txt
Labels: hacktoberfest-accepted

#7 Configuração Deploy Continuo
  Procfile
  app/extensions.py
  app/models/db.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#8 [Fix] Changing environments keys
  app/extensions.py
  app/models/db.py
  app/settings.py
Labels: enhancement, hacktoberfest-accepted

#9 BDD
  .travis.yml
  app/features/steps/tutorial.py
  app/features/tutorial.feature
  requirements.txt
Labels: hacktoberfest-accepted
